### ISSUE TITLE
ValueError: need more than 8 values to unpack

### ISSUE THREAD

**Issue by nahidbrur** [ozcell/mywork#1]
**When i ran the gar_mnist.py file, it first download the mnist data. Then the below error occur. The traceback is given below:** 
Traceback (most recent call last):
  File "gar_mnist.py", line 95, in <module>
    model_in=None)
  File "/home/nahid/projects/LALNets-master/lalnets/acol/trainings.py", line 386, in train_semisupervised
    verbose=1)
  File "/home/nahid/projects/LALNets-master/lalnets/acol/trainings.py", line 524, in train_pre
    model = define_model(*_model_params)
  File "/home/nahid/projects/LALNets-master/lalnets/acol/models.py", line 25, in define_cnn
    K, p, c1, c2, c3, c4, balance_type, pooling, trainable = acol_params
ValueError: need more than 8 values to unpack

**Where is the problem and what should i do to solve it. Thanks in advance.**

**Comment by ozcell** [comment]
Do you have the same problem in the other examples?

**Comment by EricMFischer** [comment]
I have the same problem for the SVHN dataset as well

**Comment by ozcell** [comment]
Hi Eric,

I have just committed the example codes, I hope the problem should be solved now. Please let me know in case of any further problems. 

Thanks
